// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Articles is the golang structure for table articles.
type Articles internal.Articles

// Fill with you ideas below.