// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Images is the golang structure for table images.
type Images internal.Images

// Fill with you ideas below.

type ImageApiCreateReq struct {
	ImageType int    `orm:"image_type" json:"imageType"` //
	ImageUrl  string `orm:"image_url"  json:"imageUrl"`  //
}
