// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Interviews is the golang structure for table interviews.
type Interviews internal.Interviews

// Fill with you ideas below.
type InterviewApiCreateReq struct {
	Name       string `orm:"name"        json:"Name"`       //
	CreateTime int64  `orm:"create_time" json:"CreateTime"` //
}

type InterviewsApiRep struct {
	Id         int    `orm:"id,primary"  json:"id"`         //
	Name       string `orm:"name"        json:"Name"`       //
	CreateTime int64  `orm:"create_time" json:"CreateTime"` //
	SendNumber int    `json:"SentNumber"`                   //
	PassNumber int    `json:"PassNumber"`                   //
	FailNumber int    `json:"FailNumber"`                   //
}
