// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Interviewers is the golang structure for table interviewers.
type Interviewers internal.Interviewers

// Fill with you ideas below.
type InterviewerApiCreateReq struct {
	Name           string `orm:"name"            json:"Name"`           //
	InterviewId    int    `orm:"interview_id"    json:"InterviewId"`    //
	ServerchanId   string `orm:"serverchan_id"   json:"ServerchanId"`   //
	WebhookUrl     string `orm:"webhook_url"     json:"WebhookUrl"`     //
	DepartmentType int    `orm:"department_type" json:"DepartmentType"` //
	Status         int    `orm:"status"          json:"Status"`         //
}

type InterviewersApiRep struct {
	Id             int    `orm:"id,primary"      json:"id"`             //
	Name           string `orm:"name"            json:"Name"`           //
	InterviewId    int    `orm:"interview_id"    json:"InterviewId"`    //
	ServerchanId   string `orm:"serverchan_id"   json:"ServerchanId"`   //
	WebhookUrl     string `orm:"webhook_url"     json:"WebhookUrl"`     //
	DepartmentType int    `orm:"department_type" json:"DepartmentType"` //
	Status         int    `orm:"status"          json:"Status"`         //
}
