// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Logs is the golang structure for table logs.
type Logs internal.Logs

// Fill with you ideas below.
type LogsApiRep struct {
	Id            int    `orm:"id,primary"     json:"id"`            //
	TimeStamp     int64  `orm:"time_stamp"     json:"TimeStamp"`     //
	RequestMethod string `orm:"request_method" json:"RequestMethod"` //
	Username      string `orm:"username"       json:"Username"`      //
	RequestUrl    string `orm:"request_url"    json:"RequestUrl"`    //
	ResponseName  string `orm:"response_name"  json:"ResponseName"`  //
	ModelName     string `orm:"model_name"     json:"ModelName"`     //
}
