// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Members is the golang structure for table members.
type Members internal.Members

// Fill with you ideas below.