// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Members is the golang structure for table members.
type Members internal.Members

// Fill with you ideas below.

type MemberApiCreateReq struct {
	Name        string `orm:"name"         json:"name"`        //
	UrlAvatar   string `orm:"url_avatar"   json:"urlAvatar"`   //
	SchoolYear  int    `orm:"school_year"  json:"schoolYear"`  //
	Describe    string `orm:"describe"     json:"describe"`    //
	MemberType  int    `orm:"member_type"  json:"memberType"`  //
	TeacherInfo string `orm:"teacher_info" json:"teacherInfo"` //
}
