// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Messages is the golang structure for table messages.
type Messages internal.Messages

// Fill with you ideas below.
type MessageApiCreateReq struct {
	Content    string `orm:"content"     json:"Content"`    //
	ReadStatus int    `orm:"read_status" json:"ReadStatus"` //
	CreateTime int64  `orm:"create_time" json:"CreateTime"` //
}

type MessagesApiRep struct {
	Id         int    `orm:"id,primary"  json:"id"`         //
	Content    string `orm:"content"     json:"Content"`    //
	ReadStatus int    `orm:"read_status" json:"ReadStatus"` //
	CreateTime int64  `orm:"create_time" json:"CreateTime"` //
}
