// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Passages is the golang structure for table passages.
type Passages internal.Passages

// Fill with you ideas below.

type PassageApiCreateReq struct {
	Passage string `orm:"passage"    json:"passage"` //
}

type PassagesApiRep struct {
	Id      int    `orm:"id,primary" json:"id"`      //
	Passage string `orm:"passage"    json:"Passage"` //
}
