// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Passages is the golang structure for table passages.
type Passages internal.Passages

// Fill with you ideas below.