// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Products is the golang structure for table products.
type Products internal.Products

// Fill with you ideas below.