// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"wizz-home-page/app/model/internal"
)

// Resumes is the golang structure for table resumes.
type Resumes internal.Resumes

// Fill with you ideas below.
type ResumeApiCreateReq struct {
	Describe               string `orm:"describe"                 json:"Describe"`               //
	FileUrl                string `orm:"file_url"                 json:"FileUrl"`                //
	CollegeMajor           string `orm:"college_major"            json:"CollegeMajor"`           //
	Name                   string `orm:"name"                     json:"Name"`                   //
	Gender                 int    `orm:"gender"                   json:"Gender"`                 //
	Grade                  int    `orm:"grade"                    json:"Grade"`                  //
	DepartmentType         int    `orm:"department_type"          json:"DepartmentType"`         //
	Experience             int    `orm:"experience"               json:"Experience"`             //
	InterviewId            int    `orm:"interview_id"             json:"InterviewId"`            //
	InterviewerId          int    `orm:"interviewer_id"           json:"InterviewerId"`          //
	SendTime               int64  `orm:"send_time"                json:"SendTime"`               //
	InitialScreeningResult int    `orm:"initial_screening_result" json:"InitialScreeningResult"` //
	InitialScreeningTime   int64  `orm:"initial_screening_time"   json:"InitialScreeningTime"`   //
	InterviewResult        int    `orm:"interview_result"         json:"InterviewResult"`        //
	InterviewEvaluation    string `orm:"interview_evaluation"     json:"InterviewEvaluation"`    //
	InterviewTime          int64  `orm:"interview_time"           json:"InterviewTime"`          //
}

type ResumesApiRep struct {
	Id                     int    `orm:"id,primary"               json:"id"`             //
	Describe               string `orm:"describe"                 json:"Describe"`       //
	FileUrl                string `orm:"file_url"                 json:"FileUrl"`        //
	CollegeMajor           string `orm:"college_major"            json:"CollegeMajor"`   //
	Name                   string `orm:"name"                     json:"Name"`           //
	Gender                 int    `orm:"gender"                   json:"Gender"`         //
	Grade                  int    `orm:"grade"                    json:"Grade"`          //
	DepartmentType         int    `orm:"department_type"          json:"DepartmentType"` //
	Experience             int    `orm:"experience"               json:"Experience"`     //
	InterviewId            int    `orm:"interview_id"             json:"InterviewId"`    //
	InterviewerId          int    `orm:"interviewer_id"           json:"InterviewerId"`  //
	InterviewerName        string `json:"InterviewerName"`
	SendTime               int64  `orm:"send_time"                json:"SendTime"`               //
	InitialScreeningResult int    `orm:"initial_screening_result" json:"InitialScreeningResult"` //
	InitialScreeningTime   int64  `orm:"initial_screening_time"   json:"InitialScreeningTime"`   //
	InterviewResult        int    `orm:"interview_result"         json:"InterviewResult"`        //
	InterviewEvaluation    string `orm:"interview_evaluation"     json:"InterviewEvaluation"`    //
	InterviewTime          int64  `orm:"interview_time"           json:"InterviewTime"`          //
}
