// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Images is the golang structure for table images.
type Images struct {
    Id        int    `orm:"id,primary" json:"id"`        //   
    ImageType int    `orm:"image_type" json:"imageType"` //   
    ImageUrl  string `orm:"image_url"  json:"imageUrl"`  //   
}