// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Interviewers is the golang structure for table interviewers.
type Interviewers struct {
	Id             int    `orm:"id,primary"      json:"id"`             //
	Name           string `orm:"name"            json:"name"`           //
	InterviewId    int    `orm:"interview_id"    json:"interviewId"`    //
	ServerchanId   string `orm:"serverchan_id"   json:"serverchanId"`   //
	WebhookUrl     string `orm:"webhook_url"     json:"webhookUrl"`     //
	DepartmentType int    `orm:"department_type" json:"departmentType"` //
	Status         int    `orm:"status"          json:"status"`         //
}
