// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Logs is the golang structure for table logs.
type Logs struct {
	Id            int    `orm:"id,primary"     json:"id"`            //
	TimeStamp     int64  `orm:"time_stamp"     json:"timeStamp"`     //
	RequestMethod string `orm:"request_method" json:"requestMethod"` //
	Username      string `orm:"username"       json:"username"`      //
	RequestUrl    string `orm:"request_url"    json:"requestUrl"`    //
	ResponseCode  string `orm:"response_code"  json:"responseCode"`  //
	ModelName     string `orm:"model_name"     json:"modelName"`     //
}
