// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Messages is the golang structure for table messages.
type Messages struct {
	Id         int    `orm:"id,primary"  json:"id"`         //
	Content    string `orm:"content"     json:"content"`    //
	ReadStatus int    `orm:"read_status" json:"readStatus"` //
	CreateTime int64  `orm:"create_time" json:"createTime"` //
}
