// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Passages is the golang structure for table passages.
type Passages struct {
	Id      int    `orm:"id,primary" json:"id"`      //
	Passage string `orm:"passage"    json:"passage"` //
}
