// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// Stories is the golang structure for table stories.
type Stories struct {
    Id            int    `orm:"id,primary"     json:"id"`            //   
    TimeStamp     int64  `orm:"time_stamp"     json:"timeStamp"`     //   
    Name          string `orm:"name"           json:"name"`          //   
    StoryDescribe string `orm:"story_describe" json:"storyDescribe"` //   
}