@HostName=ali.117503445.top
#@HostName=localhost
@port=8080
@host={{HostName}}:{{port}}
#身份认证使用的JWT，发出需要身份认证的请求时设置header中  Authorization: Bearer {{jwt}}
@jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODA3MDcxMTcsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTU4MDEwMjMxN30.GgawCasdti2758Kz-R7U5TK2fi48vlboiLdiUEvVAZE

@id=1

### 登录, 获取 JWT

POST http://{{host}}/api/auth/login

{
    "Username": "admin",
    "Password": "admin"
}

#{
#  "code": 200,
#  "expire": "2020-01-26T15:38:55+08:00",
#  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODAwMjQzMzUsImlkIjoiYWRtaW4iLCJv#cmlnX2lhdCI6MTU3OTQxOTUzNX0.mQzE-bFxiNeNEPGqsG8xqxhq_tEsuTkukx8v-pN0rzs"
#}



### 获取 所有 历史事件，stories
# @name getAllStories
GET http://{{host}}/api/stories

#200
#[{"id": 1,"time": 0,"name": "","storyDescribe": ""},{"id": 2,"time": 0,"name": "","storyDescribe": ""},{"id": 3,"time": 1579178477,"name": "","storyDescribe": "hello"},{"id": 4,"time": 1579178477,"name": "3","storyDescribe": "hello"}]



### 获取 id 为 {{id}} 的历史事件，stories
# @name getOneStory
@getOneStory_id=3
GET http://{{host}}/api/stories/{{getOneStory_id}}

#200
#{"id": 2,"time": 1,"name": "12","storyDescribe": "hello"}

### 获取 id 为 {{id}} 的历史事件，stories
# @name getOneStory_not_found
@getOneStory_not_found_id=6
GET http://{{host}}/api/stories/{{getOneStory_not_found_id}}

#404
#{"message": "user not found"}



### 添加 一个 历史事件，stories
POST http://{{host}}/api/stories
Authorization: Bearer {{jwt}}

{
    "time": 1579178477,
    "name": "i am name",
    "storyDescribe": "i am storyDescribe"
}

### 添加 一个 历史事件，stories，不带jwt
POST http://{{host}}/api/stories

{
    "time": 1579178477,
    "name": "i am name",
    "storyDescribe": "i am storyDescribe"
}

@updateOneStory_id=1
### 更新 某个 历史事件，stories
PUT http://{{host}}/api/stories/{{updateOneStory_id}}
Authorization: Bearer {{jwt}}

{
    "time":1576457758,
    "name":"i am newName",
    "storyDescribe":"i am new storyDescribe"
}

#无返回

@deleteOneStory_id=5
### 删除 某个 历史事件，stories
DELETE http://{{host}}/api/stories/{{deleteOneStory_id}}
Authorization: Bearer {{jwt}}

###

#无返回

