// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wizz-home-page/app/dao/internal"
)

// imagesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type imagesDao struct {
	*internal.ImagesDao
}

var (
	// Images is globally public accessible object for table images operations.
	Images = &imagesDao{
		internal.Images,
	}
)

// Fill with you ideas below.