// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wizz-home-page/app/dao/internal"
)

// messagesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type messagesDao struct {
	*internal.MessagesDao
}

var (
	// Messages is globally public accessible object for table messages operations.
	Messages = &messagesDao{
		internal.Messages,
	}
)

// Fill with you ideas below.
