// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"wizz-home-page/app/dao/internal"
)

// storiesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type storiesDao struct {
	*internal.StoriesDao
}

var (
	// Stories is globally public accessible object for table stories operations.
	Stories = &storiesDao{
		internal.Stories,
	}
)

// Fill with you ideas below.