basePath: /api
definitions:
  models.Story:
    properties:
      id:
        type: integer
      name:
        type: string
      storyDescribe:
        type: string
      time:
        type: integer
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: t117503445@gmail.com
    name: "117503445"
    url: https://github.com/117503445
  description: Wizz's HomePage Backend
  license:
    name: GNU General Public License v3.0
    url: https://github.com/TGclub/Wizz-Home-Page/blob/master/LICENSE
  title: Wizz-Home-Page API
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: 从数据库中获取用户信息
      parameters:
      - description: user id in database
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data": {}}'
          schema:
            $ref: '#/definitions/models.Story'
      security:
      - ApiKeyAuth: []
      summary: 获取用户
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
